---
- name: Update all packages to the latest version
  ansible.builtin.yum:
    name: '*'
    state: latest
  tags: os_update

- name: Clean all yum cache (optional)
  ansible.builtin.command: yum clean all
  tags: os_update

- name: Reboot if needed after update (optional)
  ansible.builtin.reboot:
    msg: "Rebooting to complete OS update"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 5
    post_reboot_delay: 10
    est_command: whoami
  tags: os_update
