---
- name: Create single partition on the disk
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: present
    fs_type: ext4
    resize: yes

- name: Install LVM2 package
  ansible.builtin.yum:
    name: lvm2
    state: present

- name: Create a physical volume
  community.general.lvm_pv:
    device: "/dev/sdb1"

- name: Create a volume group
  ansible.builtin.lvg:
    vg: "vg1"
    pvs: "/dev/sdb1"

- name: Create logical volume /data
  ansible.builtin.lvol:
    vg : "vg1"
    lv: "lv_data"
    size: 30G
  
- name: Create logical volume /logs
  ansible.builtin.lvol:
    vg: "vg1"
    lv: "lv_logs"
    size: 100%FREE
  

- name: Create filesystem on /data
  ansible.builtin.filesystem:
    fstype: ext4
    dev: "/dev/vg1/lv_data"

- name: Create filesystem on /logs
  ansible.builtin.filesystem:
    fstype: ext4
    dev: "/dev/vg1/lv_logs"

- name: Ensure /data mount exists
  ansible.builtin.file:
    path: "/data"
    state: directory
  
- name: Ensure /logs mount exists
  ansible.builtin.file:
    path: "/logs"
    state: directory

- name: Mount /data 
  ansible.builtin.mount:
    path: "/data"
    src: "/dev/vg1/lv_data"
    fstype: ext4
    state: mounted
    

- name: Mount /logs
  ansible.builtin.mount:
    path: "/logs"
    src: "/dev/vg1/lv_logs"
    fstype: ext4
    state: mounted
    