---
- name: Install mongo and setup lvm
  hosts: install_mongo
  become: true
  roles:
    - setup_mongo

- name: Install mongo and setup lvm
  hosts: install_lvm
  become: true
  roles:
    - setup_mongo